appname: denti
port: 8282
logger:
    use: zapLogger
    environment: dev
    loglevel: debug
    filename: denti.log
db:
    use: postgres
    postgres:
        enabled: true
        host: postgres
        port: 5432
        userName: postgres
        password: postgres
        database: denti
contacts:
    name: 'Akbar Shaikh'
    email: aashaikh55@gmail.com
